---
driver:
  name: vagrant

provisioner:
  name: chef_solo

verifier:
  name: inspec

platforms:
  - name: ubuntu-16.04
  - name: ubuntu-14.04
  - name: ubuntu-12.04
  - name: centos-7.3
  - name: centos-6.8

suites:
  - name: default
    run_list:
    - recipe[dns_caching::default]
    attributes:
      resolver:
        nameservers:
          - 127.0.0.1
          - 8.8.8.8
          - 8.8.4.4
