---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04
  - name: centos-6.5

suites:
  - name: default
    run_list:
    - recipe[dns_caching::default]
    attributes:
      resolver:
        nameservers:
          - 127.0.0.1
          - 8.8.8.8
          - 8.8.4.4
