name 'dns_caching'
maintainer 'Biola University'
maintainer_email 'sysadmins@biola.edu'
license 'Apache 2.0'
description 'Installs dnsmasq to provide DNS caching'
source_url 'https://github.com/biola/chef-dns_caching'
issues_url 'https://github.com/biola/chef-dns_caching/issues'
version '1.1.2'

depends 'resolver', '~> 1.1.4'
